CREATE TABLE courses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    semester INTEGER NOT NULL,
    courseFullID TEXT NOT NULL,
    courseName TEXT NOT NULL,
    courseEngName TEXT,
    department TEXT NOT NULL,
    departmentID TEXT NOT NULL,
    courseType TEXT NOT NULL,
    subjectID TEXT NOT NULL,
    subjectGroup TEXT NOT NULL,
    grade TEXT,
    classGroup TEXT,
    className TEXT,
    classID TEXT,
    credit INTEGER,
    totalOfTakingStudents INTEGER,
    numberOfTakingStudents INTEGER,
    weekNumber TEXT,
    day TEXT,
    dayNum INTEGER,
    startPeriod INTEGER,
    endPeriod INTEGER,
    startTime TEXT,
    endTime TEXT,
    courseLocation TEXT,
    mainTeacherName TEXT,
    multipleTeacherName TEXT,
    note TEXT,
    courseAbstract TEXT,
    courseEngAbstract TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(semester, courseFullID)
);